apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-ajwh
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/botheaj/cloud-run-skaffold.git
    targetRevision: HEAD
    path: ./kube

  destination:
    server: https://kubernetes.default.svc #on the same cluster, so we can use the internal address
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
