apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-skaffold
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: us-docker.pkg.dev/itx-telescope-stage-1/telescope/hello-world